2019-12-02 13:57:49,489 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 75958759, 'date': datetime.datetime(2019, 12, 2, 13, 57, 48, 615036, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 3009485, 'danmaku': 133777, 'reply': 16546, 'favorite': 59, 'coin': 26284, 'share': 657, 'now_rank': 0, 'his_rank': 0, 'like': 1027, 'dislike': 0, 'online_count': 26156}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 75958759
2019-12-02 14:00:22,715 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 75958759, 'date': datetime.datetime(2019, 12, 2, 14, 0, 21, 722520, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 3008940, 'danmaku': 133770, 'reply': 16545, 'favorite': 59, 'coin': 26284, 'share': 657, 'now_rank': 0, 'his_rank': 0, 'like': 1027, 'dislike': 0, 'online_count': 26292}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 75958759
2019-12-02 14:01:17,036 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 75958759, 'date': datetime.datetime(2019, 12, 2, 14, 1, 16, 303682, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 3010511, 'danmaku': 133800, 'reply': 16548, 'favorite': 59, 'coin': 26289, 'share': 657, 'now_rank': 0, 'his_rank': 0, 'like': 1027, 'dislike': 0, 'online_count': 25803}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 75958759
2019-12-02 14:02:47,770 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 75958759, 'date': datetime.datetime(2019, 12, 2, 14, 2, 46, 849048, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 3010511, 'danmaku': 133802, 'reply': 16548, 'favorite': 59, 'coin': 26289, 'share': 657, 'now_rank': 0, 'his_rank': 0, 'like': 1027, 'dislike': 0, 'online_count': 25803}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 75958759
2019-12-02 14:02:47,952 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77031527, 'date': datetime.datetime(2019, 12, 2, 14, 2, 47, 772020, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 1977313, 'danmaku': 76774, 'reply': 7709, 'favorite': 52, 'coin': 17257, 'share': 426, 'now_rank': 0, 'his_rank': 0, 'like': 1069, 'dislike': 0, 'online_count': 17264}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77031527
2019-12-02 14:02:48,134 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77712427, 'date': datetime.datetime(2019, 12, 2, 14, 2, 47, 954991, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 995199, 'danmaku': 12101, 'reply': 9371, 'favorite': 4529, 'coin': 2992, 'share': 1464, 'now_rank': 0, 'his_rank': 0, 'like': 14132, 'dislike': 0, 'online_count': 14971}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77712427
2019-12-02 14:02:48,316 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77742135, 'date': datetime.datetime(2019, 12, 2, 14, 2, 48, 136050, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 152125, 'danmaku': 5884, 'reply': 477, 'favorite': 1889, 'coin': 630, 'share': 84, 'now_rank': 0, 'his_rank': 0, 'like': 2616, 'dislike': 0, 'online_count': 14783}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77742135
2019-12-02 14:02:48,507 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77702585, 'date': datetime.datetime(2019, 12, 2, 14, 2, 48, 317927, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 691396, 'danmaku': 19085, 'reply': 4190, 'favorite': 2727, 'coin': 2396, 'share': 1384, 'now_rank': 0, 'his_rank': 0, 'like': 9851, 'dislike': 0, 'online_count': 8626}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77702585
2019-12-02 14:02:48,690 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77052062, 'date': datetime.datetime(2019, 12, 2, 14, 2, 48, 509828, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 1135132, 'danmaku': 52470, 'reply': 5271, 'favorite': 39, 'coin': 10029, 'share': 179, 'now_rank': 0, 'his_rank': 0, 'like': 917, 'dislike': 0, 'online_count': 8557}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77052062
2019-12-02 14:02:48,873 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77781927, 'date': datetime.datetime(2019, 12, 2, 14, 2, 48, 691327, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 153988, 'danmaku': 1256, 'reply': 565, 'favorite': 447, 'coin': 1690, 'share': 94, 'now_rank': 0, 'his_rank': 0, 'like': 4699, 'dislike': 0, 'online_count': 6721}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77781927
2019-12-02 14:02:49,060 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77771165, 'date': datetime.datetime(2019, 12, 2, 14, 2, 48, 875402, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 51455, 'danmaku': 1572, 'reply': 375, 'favorite': 84, 'coin': 449, 'share': 31, 'now_rank': 0, 'his_rank': 0, 'like': 632, 'dislike': 0, 'online_count': 6572}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77771165
2019-12-02 14:02:49,206 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77224508, 'date': datetime.datetime(2019, 12, 2, 14, 2, 49, 62385, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 2462830, 'danmaku': 37069, 'reply': 8054, 'favorite': 416698, 'coin': 540743, 'share': 63771, 'now_rank': 0, 'his_rank': 0, 'like': 389665, 'dislike': 0, 'online_count': 5802}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77224508
2019-12-02 14:02:49,438 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77743429, 'date': datetime.datetime(2019, 12, 2, 14, 2, 49, 208355, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 55162, 'danmaku': 3344, 'reply': 180, 'favorite': 215, 'coin': 525, 'share': 62, 'now_rank': 0, 'his_rank': 0, 'like': 1476, 'dislike': 0, 'online_count': 4369}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77743429
2019-12-02 14:02:49,595 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77653920, 'date': datetime.datetime(2019, 12, 2, 14, 2, 49, 441253, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 832745, 'danmaku': 1850, 'reply': 634, 'favorite': 11157, 'coin': 1788, 'share': 6192, 'now_rank': 0, 'his_rank': 0, 'like': 9907, 'dislike': 0, 'online_count': 3720}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77653920
2019-12-02 14:02:49,784 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77786436, 'date': datetime.datetime(2019, 12, 2, 14, 2, 49, 597615, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 31913, 'danmaku': 779, 'reply': 1010, 'favorite': 657, 'coin': 1508, 'share': 63, 'now_rank': 0, 'his_rank': 0, 'like': 4249, 'dislike': 0, 'online_count': 3667}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77786436
2019-12-02 14:02:49,989 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77791127, 'date': datetime.datetime(2019, 12, 2, 14, 2, 49, 786864, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 23126, 'danmaku': 204, 'reply': 339, 'favorite': 420, 'coin': 406, 'share': 52, 'now_rank': 0, 'his_rank': 0, 'like': 1937, 'dislike': 0, 'online_count': 3285}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77791127
2019-12-02 14:02:50,395 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77425344, 'date': datetime.datetime(2019, 12, 2, 14, 2, 49, 991679, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 1081497, 'danmaku': 23199, 'reply': 7060, 'favorite': 6, 'coin': 12108, 'share': 75, 'now_rank': 0, 'his_rank': 0, 'like': 498, 'dislike': 0, 'online_count': 3051}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77425344
2019-12-02 14:02:50,542 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 51121699, 'date': datetime.datetime(2019, 12, 2, 14, 2, 50, 397303, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 19545577, 'danmaku': 68041, 'reply': 19001, 'favorite': 258121, 'coin': 244269, 'share': 34094, 'now_rank': 0, 'his_rank': 36, 'like': 184621, 'dislike': 0, 'online_count': 3050}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 51121699
2019-12-02 14:02:50,730 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77420167, 'date': datetime.datetime(2019, 12, 2, 14, 2, 50, 543127, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 1059504, 'danmaku': 15807, 'reply': 2452, 'favorite': 6, 'coin': 6799, 'share': 41, 'now_rank': 0, 'his_rank': 0, 'like': 571, 'dislike': 0, 'online_count': 2917}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77420167
2019-12-02 14:02:50,927 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77719360, 'date': datetime.datetime(2019, 12, 2, 14, 2, 50, 732177, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 289947, 'danmaku': 5008, 'reply': 2015, 'favorite': 2322, 'coin': 5457, 'share': 732, 'now_rank': 0, 'his_rank': 0, 'like': 16975, 'dislike': 0, 'online_count': 2883}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77719360
2019-12-02 14:02:51,070 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77693862, 'date': datetime.datetime(2019, 12, 2, 14, 2, 50, 929382, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 411841, 'danmaku': 2708, 'reply': 394, 'favorite': 1854, 'coin': 5807, 'share': 640, 'now_rank': 0, 'his_rank': 0, 'like': 12595, 'dislike': 0, 'online_count': 2238}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77693862
2019-12-02 14:02:51,224 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77342611, 'date': datetime.datetime(2019, 12, 2, 14, 2, 51, 72708, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 799163, 'danmaku': 6465, 'reply': 2820, 'favorite': 2177, 'coin': 11857, 'share': 1053, 'now_rank': 0, 'his_rank': 0, 'like': 39624, 'dislike': 0, 'online_count': 1826}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77342611
2019-12-02 14:02:51,409 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:50] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77241823, 'date': datetime.datetime(2019, 12, 2, 14, 2, 51, 226655, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 2749150, 'danmaku': 48645, 'reply': 10552, 'favorite': 14, 'coin': 19644, 'share': 355, 'now_rank': 0, 'his_rank': 0, 'like': 642, 'dislike': 0, 'online_count': 1681}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77241823
2019-12-02 14:02:51,414 - [    INFO] - [          MainThread]   __init__.<module> - __init__.py[line:67] : Done
2019-12-02 14:07:08,918 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 75958759, 'date': datetime.datetime(2019, 12, 2, 14, 7, 8, 104849, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 3015065, 'danmaku': 136399, 'reply': 16556, 'favorite': 59, 'coin': 26318, 'share': 657, 'now_rank': 0, 'his_rank': 0, 'like': 1028, 'dislike': 0, 'online_count': 24563}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 75958759
2019-12-02 14:07:09,065 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77031527, 'date': datetime.datetime(2019, 12, 2, 14, 7, 8, 918383, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 1981090, 'danmaku': 76868, 'reply': 7717, 'favorite': 52, 'coin': 17275, 'share': 426, 'now_rank': 0, 'his_rank': 0, 'like': 1069, 'dislike': 0, 'online_count': 16460}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77031527
2019-12-02 14:07:09,214 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77712427, 'date': datetime.datetime(2019, 12, 2, 14, 7, 9, 66960, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 999322, 'danmaku': 12145, 'reply': 9368, 'favorite': 4543, 'coin': 3013, 'share': 1469, 'now_rank': 0, 'his_rank': 0, 'like': 14174, 'dislike': 0, 'online_count': 13905}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77712427
2019-12-02 14:07:09,365 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77742135, 'date': datetime.datetime(2019, 12, 2, 14, 7, 9, 215795, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 153734, 'danmaku': 5965, 'reply': 477, 'favorite': 1895, 'coin': 635, 'share': 85, 'now_rank': 0, 'his_rank': 0, 'like': 2634, 'dislike': 0, 'online_count': 13458}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77742135
2019-12-02 14:07:09,556 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77052062, 'date': datetime.datetime(2019, 12, 2, 14, 7, 9, 365393, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 1137100, 'danmaku': 52536, 'reply': 5273, 'favorite': 39, 'coin': 10040, 'share': 179, 'now_rank': 0, 'his_rank': 0, 'like': 918, 'dislike': 0, 'online_count': 8180}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77052062
2019-12-02 14:07:09,708 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77702585, 'date': datetime.datetime(2019, 12, 2, 14, 7, 9, 557675, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 693726, 'danmaku': 19142, 'reply': 4200, 'favorite': 2735, 'coin': 2410, 'share': 1387, 'now_rank': 0, 'his_rank': 0, 'like': 9881, 'dislike': 0, 'online_count': 7997}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77702585
2019-12-02 14:07:09,898 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77781927, 'date': datetime.datetime(2019, 12, 2, 14, 7, 9, 709857, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 160068, 'danmaku': 1277, 'reply': 572, 'favorite': 469, 'coin': 1773, 'share': 96, 'now_rank': 0, 'his_rank': 0, 'like': 4867, 'dislike': 0, 'online_count': 6602}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77781927
2019-12-02 14:07:10,091 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77771165, 'date': datetime.datetime(2019, 12, 2, 14, 7, 9, 898605, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 52920, 'danmaku': 1642, 'reply': 381, 'favorite': 86, 'coin': 457, 'share': 31, 'now_rank': 0, 'his_rank': 0, 'like': 648, 'dislike': 0, 'online_count': 6347}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77771165
2019-12-02 14:07:10,253 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 73933928, 'date': datetime.datetime(2019, 12, 2, 14, 7, 10, 91591, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 6373585, 'danmaku': 422073, 'reply': 37678, 'favorite': 485, 'coin': 38852, 'share': 1372, 'now_rank': 0, 'his_rank': 0, 'like': 3116, 'dislike': 0, 'online_count': 6006}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 73933928
2019-12-02 14:07:10,403 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77754136, 'date': datetime.datetime(2019, 12, 2, 14, 7, 10, 253311, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 41286, 'danmaku': 1876, 'reply': 193, 'favorite': 592, 'coin': 67, 'share': 65, 'now_rank': 0, 'his_rank': 0, 'like': 849, 'dislike': 0, 'online_count': 5836}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77754136
2019-12-02 14:07:10,561 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77743429, 'date': datetime.datetime(2019, 12, 2, 14, 7, 10, 404831, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 55857, 'danmaku': 3360, 'reply': 181, 'favorite': 216, 'coin': 531, 'share': 63, 'now_rank': 0, 'his_rank': 0, 'like': 1486, 'dislike': 0, 'online_count': 4027}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77743429
2019-12-02 14:07:10,757 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77786436, 'date': datetime.datetime(2019, 12, 2, 14, 7, 10, 562042, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 39002, 'danmaku': 915, 'reply': 1082, 'favorite': 793, 'coin': 1833, 'share': 80, 'now_rank': 0, 'his_rank': 0, 'like': 5060, 'dislike': 0, 'online_count': 3659}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77786436
2019-12-02 14:07:10,950 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77791127, 'date': datetime.datetime(2019, 12, 2, 14, 7, 10, 757380, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 35061, 'danmaku': 266, 'reply': 385, 'favorite': 632, 'coin': 571, 'share': 78, 'now_rank': 0, 'his_rank': 0, 'like': 2798, 'dislike': 0, 'online_count': 3518}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77791127
2019-12-02 14:07:11,145 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 12346469, 'date': datetime.datetime(2019, 12, 2, 14, 7, 10, 951990, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 39305334, 'danmaku': 1458531, 'reply': 36152, 'favorite': 297293, 'coin': 71049, 'share': 40868, 'now_rank': 0, 'his_rank': 0, 'like': 29629, 'dislike': 0, 'online_count': 3462}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 12346469
2019-12-02 14:07:11,342 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 32675854, 'date': datetime.datetime(2019, 12, 2, 14, 7, 11, 146163, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 40271322, 'danmaku': 1327709, 'reply': 82012, 'favorite': 1496, 'coin': 127244, 'share': 37973, 'now_rank': 0, 'his_rank': 0, 'like': 2388, 'dislike': 0, 'online_count': 3201}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 32675854
2019-12-02 14:07:11,533 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77719360, 'date': datetime.datetime(2019, 12, 2, 14, 7, 11, 343758, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 291067, 'danmaku': 5023, 'reply': 2018, 'favorite': 2328, 'coin': 5465, 'share': 734, 'now_rank': 0, 'his_rank': 0, 'like': 17022, 'dislike': 0, 'online_count': 2721}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77719360
2019-12-02 14:07:11,692 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77629043, 'date': datetime.datetime(2019, 12, 2, 14, 7, 11, 533981, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 285748, 'danmaku': 10043, 'reply': 459, 'favorite': 3900, 'coin': 621, 'share': 382, 'now_rank': 0, 'his_rank': 0, 'like': 4111, 'dislike': 0, 'online_count': 2659}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77629043
2019-12-02 14:07:11,903 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77716219, 'date': datetime.datetime(2019, 12, 2, 14, 7, 11, 692595, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 345633, 'danmaku': 2197, 'reply': 8987, 'favorite': 10256, 'coin': 25030, 'share': 8212, 'now_rank': 0, 'his_rank': 0, 'like': 31637, 'dislike': 0, 'online_count': 2585}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77716219
2019-12-02 14:07:12,089 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 77698716, 'date': datetime.datetime(2019, 12, 2, 14, 7, 11, 903470, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 547890, 'danmaku': 1237, 'reply': 842, 'favorite': 6657, 'coin': 23092, 'share': 7470, 'now_rank': 0, 'his_rank': 0, 'like': 35300, 'dislike': 0, 'online_count': 2130}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 77698716
2019-12-02 14:07:12,265 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.InternalError) (1054, "Unknown column 'date' in 'field list'")
[SQL: INSERT INTO av_stat (aid, date, view, danmaku, reply, favorite, coin, share, now_rank, his_rank, `like`, dislike, online_count) VALUES (%(aid)s, %(date)s, %(view)s, %(danmaku)s, %(reply)s, %(favorite)s, %(coin)s, %(share)s, %(now_rank)s, %(his_rank)s, %(like)s, %(dislike)s, %(online_count)s)]
[parameters: {'aid': 47508491, 'date': datetime.datetime(2019, 12, 2, 14, 7, 12, 89984, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'view': 26415719, 'danmaku': 1526405, 'reply': 61917, 'favorite': 17856, 'coin': 228380, 'share': 35366, 'now_rank': 0, 'his_rank': 0, 'like': 12449, 'dislike': 0, 'online_count': 1850}]
(Background on this error at: http://sqlalche.me/e/2j85), aid: 47508491
2019-12-02 14:07:12,265 - [    INFO] - [          MainThread]   __init__.<module> - __init__.py[line:67] : Done
2019-12-02 14:08:40,523 - [    INFO] - [          MainThread]   __init__.<module> - __init__.py[line:67] : Done
2019-12-02 14:12:58,412 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 75958759, 'videos': 26, 'tid': 32, 'tname': '完结动画', 'copyright': 2, 'pic': 'http://i1.hdslb.com/bfs/archive/73e2deab91e3fc493a7cb077c26b0e56d1baa69d.jpg', 'title': 'JOJO的奇妙冒险', 'pubdate': datetime.datetime(2019, 11, 30, 0, 0, 2, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 11, 17, 9, 57, 13, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': '在古代墨西哥繁盛一时的太阳的子民阿兹特克，他们流传着一枚奇妙的「石鬼面」。那是一枚奇迹的面具，能让人拥有一种力量，能获得永远的生命并成为真正的掌控者。然而从某个时候开始，就从历史中消失了踪影。时光飞逝，来到了19世纪后叶。在这个人们的思想与生活产生激烈变化的时代，乔纳森·乔斯达与迪奥·布兰度相遇。二人一同渡过了少年时代到青年时代，最后因为「石鬼面」，而步上了奇特怪异的命运。', 'state': 0, 'attribute': 76544, 'duration': 36931, 'mission_id': -1, 'dynamic': '', 'cid': 131624280, 'bvid': '', 'owner_mid': 928123, 'stat_aid': 75958759, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 0, 'right_hd5': 1, 'right_no_reprint': 0, 'right_autoplay': 0, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1920, 'dimension_height': 1080, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 12, 57, 425689, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 75958759
2019-12-02 14:12:58,574 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 77031527, 'videos': 24, 'tid': 32, 'tname': '完结动画', 'copyright': 2, 'pic': 'http://i2.hdslb.com/bfs/archive/1cbff3ae0089d142564c8d1ae947a7360e486baf.jpg', 'title': 'JOJO的奇妙冒险  星尘远征军', 'pubdate': datetime.datetime(2019, 11, 30, 0, 0, 3, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 11, 26, 8, 59, 43, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': '时为1987年，乔瑟夫·乔斯达与“柱之男”们之间的死战后过了50年……乔瑟夫为了为了帮助“被恶灵附身了”的外孙子·空条承太郎而来到了日本。原来那并不是恶灵而是幽波纹（替身）。替身突然出现的原因在于，从跨越100年的长眠中苏醒过来的吸血鬼·DIO与乔斯达家之间的令人忌讳的因缘。为了拯救受到DIO的诅咒而倒下的承太郎的母亲·荷莉，他们决定要打倒邪恶的化身·DIO，和伙伴们一起踏上了旅程。', 'state': 0, 'attribute': 338688, 'duration': 34569, 'mission_id': -1, 'dynamic': '', 'cid': 131734643, 'bvid': '', 'owner_mid': 928123, 'stat_aid': 77031527, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 1, 'right_hd5': 1, 'right_no_reprint': 0, 'right_autoplay': 0, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1920, 'dimension_height': 1080, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 12, 58, 413415, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 77031527
2019-12-02 14:12:58,734 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 77712427, 'videos': 2, 'tid': 171, 'tname': '电子竞技', 'copyright': 1, 'pic': 'http://i2.hdslb.com/bfs/archive/4bca1e3273813c01bc3e293619014daca292bfc1.jpg', 'title': 'LPL全明星周末D2全明星正赛', 'pubdate': datetime.datetime(2019, 12, 1, 19, 6, 24, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 12, 1, 19, 6, 24, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': 'LPL全明星周末D2全明星正赛', 'state': 0, 'attribute': 16384, 'duration': 5872, 'mission_id': -1, 'dynamic': '#电子竞技##英雄联盟##LPL全明星#LPL全明星周末D2全明星正赛', 'cid': 132951102, 'bvid': '', 'owner_mid': 50329118, 'stat_aid': 77712427, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 0, 'right_hd5': 0, 'right_no_reprint': 0, 'right_autoplay': 1, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1920, 'dimension_height': 1080, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 12, 58, 575088, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 77712427
2019-12-02 14:12:58,897 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 77742135, 'videos': 1, 'tid': 131, 'tname': 'Korea相关', 'copyright': 2, 'pic': 'http://i0.hdslb.com/bfs/archive/8ad00b2d0c7f2b41f47a712fd55199fd05f5b2ee.jpg', 'title': '[TSKS]Running Man.E479.191201.中字', 'pubdate': datetime.datetime(2019, 12, 1, 23, 34, 32, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 12, 1, 23, 34, 33, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': 'TSKS团结才能生存的全员通过竞赛：与怀疑同行。惩罚是召唤勇度装扮，卖出100个鲫鱼饼。羡慕溜三丝热度的54哥，既上周被PD掐断话头后，继续被无视。成员们扔硬币可以达到目标金额吗？末等长颈鹿可以逆袭成功吗？', 'state': 0, 'attribute': 16384, 'duration': 4965, 'mission_id': -1, 'dynamic': '#Running Man#', 'cid': 132999652, 'bvid': '', 'owner_mid': 43389575, 'stat_aid': 77742135, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 0, 'right_hd5': 0, 'right_no_reprint': 0, 'right_autoplay': 1, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1280, 'dimension_height': 720, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 12, 58, 735277, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 77742135
2019-12-02 14:12:59,058 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 77052062, 'videos': 24, 'tid': 32, 'tname': '完结动画', 'copyright': 2, 'pic': 'http://i2.hdslb.com/bfs/archive/9ce4575a7a3478ceee8400396555de002d430bb3.jpg', 'title': 'JOJO的奇妙冒险 星尘远征军 埃及篇', 'pubdate': datetime.datetime(2019, 11, 30, 0, 0, 3, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 11, 26, 8, 59, 18, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': '在乔斯达家的宿敌·迪奥（DIO）复活的影响下，一位年轻人——空条承太郎，得到了名为“幽波纹（替身）”的能力。为了拯救因迪奥的诅咒而倒下的母亲荷莉，空条承太郎与外祖父·乔瑟夫以及伙伴们，一起为了打倒迪奥而展开旅程。在漫长的旅途当中，承太郎等人一次又一次地击退刺客，最后终于抵达迪奥所在的埃及。然而，为了阻止他们前进，各种怪异可怕的新一波敌影不断逼近——', 'state': 0, 'attribute': 338688, 'duration': 34582, 'mission_id': -1, 'dynamic': '', 'cid': 131792259, 'bvid': '', 'owner_mid': 928123, 'stat_aid': 77052062, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 1, 'right_hd5': 1, 'right_no_reprint': 0, 'right_autoplay': 0, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1920, 'dimension_height': 1080, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 12, 58, 897675, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 77052062
2019-12-02 14:12:59,261 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 77702585, 'videos': 2, 'tid': 171, 'tname': '电子竞技', 'copyright': 1, 'pic': 'http://i0.hdslb.com/bfs/archive/04d44dbadf44de9fc99206f5cb2d0f9a11c94e8f.jpg', 'title': 'LPL全明星周末D2传奇对抗赛', 'pubdate': datetime.datetime(2019, 12, 1, 17, 45, 32, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 12, 1, 17, 45, 32, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': 'LPL全明星周末D2传奇对抗赛', 'state': 0, 'attribute': 16384, 'duration': 4784, 'mission_id': -1, 'dynamic': '#电子竞技##英雄联盟##LPL全明星#LPL全明星周末D2传奇对抗赛', 'cid': 132934120, 'bvid': '', 'owner_mid': 50329118, 'stat_aid': 77702585, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 0, 'right_hd5': 0, 'right_no_reprint': 0, 'right_autoplay': 1, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1920, 'dimension_height': 1080, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 12, 59, 59325, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 77702585
2019-12-02 14:12:59,422 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 77781927, 'videos': 1, 'tid': 171, 'tname': '电子竞技', 'copyright': 1, 'pic': 'http://i1.hdslb.com/bfs/archive/c42309171df86a3c077f4f83416d624a2cd92565.jpg', 'title': '炉石传说：【天天素材库】 第173期', 'pubdate': datetime.datetime(2019, 12, 2, 11, 59, 31, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 12, 2, 11, 59, 32, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': '天天卡牌出品 《天天素材库》每周一更新 微博@逗鱼时刻 微信公众号:ttkapai炉石投稿邮箱:ttkapai@qq.com商务合作邮箱:ttkapai_hz@163.com粉丝扣扣大本营一号：112678056', 'state': 0, 'attribute': 16768, 'duration': 516, 'mission_id': -1, 'dynamic': '#逗鱼时刻##炉石传说##天天卡牌#', 'cid': 133069865, 'bvid': '', 'owner_mid': 10462362, 'stat_aid': 77781927, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 0, 'right_hd5': 1, 'right_no_reprint': 1, 'right_autoplay': 1, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1920, 'dimension_height': 1080, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 12, 59, 261934, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 77781927
2019-12-02 14:12:59,650 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 77771165, 'videos': 10, 'tid': 171, 'tname': '电子竞技', 'copyright': 1, 'pic': 'http://i0.hdslb.com/bfs/archive/a5a64ce1a5211c95a66f89ec21f73554358d54c7.png', 'title': '神探西卡李性分析：到底是谁萨了鼠标垫？', 'pubdate': datetime.datetime(2019, 12, 2, 9, 35, 11, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 12, 2, 9, 35, 11, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': '德云色直播间：https://egame.qq.com/497383565\r微博：@小孩kiddddd@dys释梦 @笑笑_孙亚龙 @西卡_李浩宇 @dys米米 @dys元气\r百度贴吧：德云色', 'state': 0, 'attribute': 16512, 'duration': 30961, 'mission_id': -1, 'dynamic': '', 'cid': 133043976, 'bvid': '', 'owner_mid': 8739477, 'stat_aid': 77771165, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 0, 'right_hd5': 0, 'right_no_reprint': 1, 'right_autoplay': 1, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1920, 'dimension_height': 1080, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 12, 59, 422346, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 77771165
2019-12-02 14:12:59,812 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 73933928, 'videos': 167, 'tid': 32, 'tname': '完结动画', 'copyright': 2, 'pic': 'http://i1.hdslb.com/bfs/archive/946cd945f0300f5049a07611b8737a717e93c6ef.jpg', 'title': '犬夜叉', 'pubdate': datetime.datetime(2019, 11, 1, 17, 59, 59, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 10, 30, 17, 53, 5, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': '《犬夜叉》是根据日本漫画家高桥留美子所著同名作品改编的电视动画，故事讲述半妖少年——犬夜叉和穿越时空的少女——日暮戈薇，以及法师弥勒、驱魔师珊瑚、叉尾妖猫云母、小狐妖七宝一同对抗死敌奈落，并四处寻找四魂之玉碎片的冒险经历。', 'state': 0, 'attribute': 77568, 'duration': 244038, 'mission_id': -1, 'dynamic': '', 'cid': 126445964, 'bvid': '', 'owner_mid': 928123, 'stat_aid': 73933928, 'right_bp': 1, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 0, 'right_hd5': 1, 'right_no_reprint': 0, 'right_autoplay': 0, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1440, 'dimension_height': 1080, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 12, 59, 650292, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 73933928
2019-12-02 14:13:00,021 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 77754136, 'videos': 1, 'tid': 131, 'tname': 'Korea相关', 'copyright': 2, 'pic': 'http://i0.hdslb.com/bfs/archive/0155b861b372331039670979a448b3cd1a49033c.jpg', 'title': '[TSKS]超人回来了.E314.191201.中字', 'pubdate': datetime.datetime(2019, 12, 2, 11, 29, 30, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 12, 2, 0, 35, 23, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': 'TSKSJamJam参加儿童电动车俱乐部被开跑车的小哥哥拐走，丢下文熙俊独自吃饭；威廉到处签上120，威廉=120？威本联盟集体购物，不买玩具，买枕头？', 'state': 0, 'attribute': 16384, 'duration': 4712, 'mission_id': -1, 'dynamic': '#超人回来了#', 'cid': 133063043, 'bvid': '', 'owner_mid': 43389575, 'stat_aid': 77754136, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 0, 'right_hd5': 0, 'right_no_reprint': 0, 'right_autoplay': 1, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1280, 'dimension_height': 720, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 12, 59, 812420, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 77754136
2019-12-02 14:13:00,181 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 77224508, 'videos': 1, 'tid': 27, 'tname': '综合', 'copyright': 1, 'pic': 'http://i2.hdslb.com/bfs/archive/93679b86f3e6689ab6283f9dc7481b77c8dcc30f.jpg', 'title': '73分钟看完柯南所有剧情！史上最全时间线整理！', 'pubdate': datetime.datetime(2019, 11, 28, 12, 0, 9, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 11, 27, 20, 20, 14, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': '73分钟看完柯南所有剧情，完整的时间线剧情大串联，从柯南变小的第一集讲到目前连载的1043话。如果你没有看过柯南任何一集，看完这个视频也能知道过去25年柯南连载的所有主线剧情；如果你看过柯南的部分剧集，这个视频将会为你梳理柯南的时间线。制作这个视频整整花了我三个月时间，如果大家觉得还不错的话，欢迎【长按点赞按钮】一键三连支持一下，希望收藏可以过万，之后也会继续做跟柯南相关的影片！感谢！', 'state': 0, 'attribute': 16768, 'duration': 4439, 'mission_id': -1, 'dynamic': '人生第一次整整花了三个月时间完成的视频《73分钟看完柯南所有剧情，史上最全的柯南时间线整理。》其实一直对粉丝挺愧疚的，三个月里没有时间更新其他视频了，希望这个大工程量的片子可以让你满意。如果大家觉得还不错的话，【长按点赞按钮】一键三连支持一下，希望收藏可以过万，之后也会继续做跟柯南相关的影片！之后的12月会更新8期视频，感谢！', 'cid': 132084205, 'bvid': '', 'owner_mid': 14068111, 'stat_aid': 77224508, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 0, 'right_hd5': 1, 'right_no_reprint': 1, 'right_autoplay': 1, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1920, 'dimension_height': 1080, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 13, 0, 22705, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 77224508
2019-12-02 14:13:00,344 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 77743429, 'videos': 2, 'tid': 131, 'tname': 'Korea相关', 'copyright': 2, 'pic': 'http://i1.hdslb.com/bfs/archive/e886b0da589b01d2333a99db5f5ed374526bb143.jpg', 'title': '【SBS综艺】Running Man E479.191201 与不信任同行 全体一致竞赛 【TSKS】', 'pubdate': datetime.datetime(2019, 12, 1, 23, 30, 13, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 12, 1, 23, 30, 13, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': '..2019合集：av40112794；2018合集：av18089528；2017合集：av12551207E479.191201 与不信任同行 全体一致竞赛嘉宾：无成员：刘在石 金钟国 宋智孝 HAHA 李光洙 池石镇 梁世赞 全昭旻', 'state': 0, 'attribute': 16384, 'duration': 5003, 'mission_id': -1, 'dynamic': '#Korea相关##RUNNINGMAN##刘在石##金钟国##宋智孝#E479.191201 与不信任同行 全体一致竞赛嘉宾：无', 'cid': 133001663, 'bvid': '', 'owner_mid': 27580511, 'stat_aid': 77743429, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 0, 'right_hd5': 0, 'right_no_reprint': 0, 'right_autoplay': 1, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1280, 'dimension_height': 720, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 13, 0, 182547, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 77743429
2019-12-02 14:13:00,547 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 77786436, 'videos': 1, 'tid': 17, 'tname': '单机游戏', 'copyright': 1, 'pic': 'http://i2.hdslb.com/bfs/archive/de5bebb70fa1429dc4a8f89b366e6afea828433f.jpg', 'title': '爸爸村历险记', 'pubdate': datetime.datetime(2019, 12, 2, 13, 16, 21, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 12, 2, 13, 16, 21, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': '讲究人都一键三连，并且点了个关注。', 'state': 0, 'attribute': 20608, 'duration': 465, 'mission_id': -1, 'dynamic': '爸爸村里各位都是爸爸。', 'cid': 133064077, 'bvid': '', 'owner_mid': 1577804, 'stat_aid': 77786436, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 0, 'right_hd5': 0, 'right_no_reprint': 1, 'right_autoplay': 1, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1920, 'dimension_height': 1080, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 13, 0, 344437, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 77786436
2019-12-02 14:13:00,708 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 12346469, 'videos': 100, 'tid': 185, 'tname': '国产剧', 'copyright': 2, 'pic': 'http://i2.hdslb.com/bfs/archive/e5980e2e23348b49f1d464147ebcdbe7e2dccb39.png', 'title': '【喜剧/家庭】家有儿女第一季 100集全【2004】', 'pubdate': datetime.datetime(2017, 7, 20, 12, 10, 5, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2017, 7, 19, 10, 26, 43, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': '儿童编导夏东海（高亚麟 饰）离婚后带着儿子夏雨（尤浩然 饰）回国发展，与在国内长大的女儿夏雪（杨紫 饰）团聚了。后来夏东海跟某医院护士长刘梅（宋丹丹 饰）结婚了，刘梅也是离婚了独自带着儿子刘星（张一山 饰）生活。这个一家5口的重组家庭，夫妻两人都非常关心孩子们的健康成长，但教育方式的不同，而且孩子们都十分调皮捣蛋，闹出了不少令人捧腹大笑却又让人深思的故事', 'state': 0, 'attribute': 107008, 'duration': 150509, 'mission_id': -1, 'dynamic': '', 'cid': 20336870, 'bvid': '', 'owner_mid': 4856007, 'stat_aid': 12346469, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 0, 'right_hd5': 0, 'right_no_reprint': 0, 'right_autoplay': 0, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 0, 'dimension_height': 0, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 13, 0, 548177, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 12346469
2019-12-02 14:13:00,869 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 32675854, 'videos': 39, 'tid': 32, 'tname': '完结动画', 'copyright': 2, 'pic': 'http://i2.hdslb.com/bfs/archive/6e169d0377956f6fac23bb85331bf77b45f21cec.jpg', 'title': '【合集】JOJO的奇妙冒险 不灭钻石【独家正版】', 'pubdate': datetime.datetime(2018, 10, 1, 16, 0, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2018, 9, 30, 11, 10, 9, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': '在埃及与宿敌DIO的死斗之后过了11年。1999年，空条承太郎为了与祖父乔瑟夫·乔斯达的私生子东方仗助见面，而来到了日本M县S市杜王町。但，仗助却持有与承太郎相同的特殊能力“替身”。之后，以承太郎的来访为开端，仿佛被吸引一般，新的“替身使”们开始行动。“这座城镇存在着什么……”为了守护养育了自己的杜王町，仗助挺身而出——', 'state': 0, 'attribute': 355072, 'duration': 56197, 'mission_id': -1, 'dynamic': '', 'cid': 61168464, 'bvid': '', 'owner_mid': 928123, 'stat_aid': 32675854, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 1, 'right_hd5': 1, 'right_no_reprint': 0, 'right_autoplay': 0, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 0, 'dimension_height': 0, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 13, 0, 708235, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 32675854
2019-12-02 14:13:01,033 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 77716219, 'videos': 1, 'tid': 21, 'tname': '日常', 'copyright': 1, 'pic': 'http://i2.hdslb.com/bfs/archive/4138ec864d17d7d5a2da273d2fe5f646c5bcd964.jpg', 'title': '比网易还狠！华为12年老员工被诉敲诈，羁押251天后被无罪释放', 'pubdate': datetime.datetime(2019, 12, 1, 20, 7, 26, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 12, 1, 20, 7, 27, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': '余不帅原创视频', 'state': 0, 'attribute': 16512, 'duration': 304, 'mission_id': -1, 'dynamic': '继#网易#赶走患病员工之后，#华为#送员工进了看守所羁押#251#天。', 'cid': 132956787, 'bvid': '', 'owner_mid': 365517, 'stat_aid': 77716219, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 0, 'right_hd5': 0, 'right_no_reprint': 1, 'right_autoplay': 1, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1920, 'dimension_height': 1080, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 13, 0, 870197, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 77716219
2019-12-02 14:13:01,239 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 77420013, 'videos': 1, 'tid': 33, 'tname': '连载动画', 'copyright': 2, 'pic': 'http://i0.hdslb.com/bfs/archive/2f372901909ea7c928a2062e72af50f8d4aff890.jpg', 'title': '【10月】命运-冠位指定 绝对魔兽战线 巴比伦尼亚 第9节【独家正版】', 'pubdate': datetime.datetime(2019, 12, 1, 0, 0, 3, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 11, 29, 15, 30, 14, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': '#第9节', 'state': 0, 'attribute': 338688, 'duration': 1461, 'mission_id': -1, 'dynamic': '', 'cid': 132441486, 'bvid': '', 'owner_mid': 928123, 'stat_aid': 77420013, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 1, 'right_hd5': 1, 'right_no_reprint': 0, 'right_autoplay': 0, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1920, 'dimension_height': 1080, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 13, 1, 33697, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 77420013
2019-12-02 14:13:01,403 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 77114195, 'videos': 10, 'tid': 172, 'tname': '手机游戏', 'copyright': 1, 'pic': 'http://i2.hdslb.com/bfs/archive/1108f1e9213e5f27822e52e709de5ec5635d3230.jpg', 'title': '【小狼XF】CB-EX全关卡 平均精一50级攻略《明日方舟》喧闹法则 CB-EX8 CB-EX45678', 'pubdate': datetime.datetime(2019, 11, 26, 19, 3, 33, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 11, 26, 19, 3, 33, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': 'EX8的2P是一个突袭的思路，有人说这样打过了确切说是最初我以为要评定就不能开装置……导致做了个普通图不开装置的打法，结果竟然能开装置反正也没浪费，突袭可以用，因为突袭要很久才能开装置。3P拿2P思路的实战实际上是很容易就过了的，感觉配置可以降低装置也没开全。只是在2P的基础上开启了一下装置，实际上还是建议看2P=========求【点赞】【硬币】【收藏】晚上7点左右B站直播↓↓↓↓周一周四不播 http://live.bilibili.com/846315更多攻略、同人 欢迎关注微', 'state': 0, 'attribute': 16512, 'duration': 3303, 'mission_id': -1, 'dynamic': '#小狼XF##明日方舟##手机游戏#', 'cid': 131901176, 'bvid': '', 'owner_mid': 298484, 'stat_aid': 77114195, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 0, 'right_hd5': 0, 'right_no_reprint': 1, 'right_autoplay': 1, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1920, 'dimension_height': 1080, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 13, 1, 240017, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 77114195
2019-12-02 14:13:01,612 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 77630961, 'videos': 10, 'tid': 131, 'tname': 'Korea相关', 'copyright': 2, 'pic': 'http://i0.hdslb.com/bfs/archive/4aed6c6b28fb8de7eecad57813e5c03bf5b05a83.jpg', 'title': '【WNS中字&多机位合集】191130 2019 MMA 防弹少年团 颁奖+舞台 cut', 'pubdate': datetime.datetime(2019, 12, 1, 4, 54, 52, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 12, 1, 4, 54, 52, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': 'kakao片源：烧麦 驴打滚制作：蓝波【禁二传涂改logo】金南俊 金硕珍 闵玧其 郑号锡 朴智旻 金泰亨 田柾国 BTS', 'state': 0, 'attribute': 16640, 'duration': 22055, 'mission_id': -1, 'dynamic': '#Korea相关##防弹少年团##防弹少年团BTS#', 'cid': 132931303, 'bvid': '', 'owner_mid': 14025362, 'stat_aid': 77630961, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 0, 'right_hd5': 1, 'right_no_reprint': 0, 'right_autoplay': 1, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1920, 'dimension_height': 1080, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 13, 1, 403067, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 77630961
2019-12-02 14:13:01,791 - [   ERROR] - [          MainThread]   __init__.<module> - __init__.py[line:54] : error: (pymysql.err.IntegrityError) (1048, "Column 'create_time' cannot be null")
[SQL: INSERT INTO av_info (aid, videos, tid, tname, copyright, pic, title, pubdate, ctime, `desc`, state, attribute, duration, mission_id, dynamic, cid, bvid, owner_mid, stat_aid, right_bp, right_elec, right_download, right_movie, right_pay, right_hd5, right_no_reprint, right_autoplay, right_ugc_pay, right_is_cooperation, right_ugc_pay_preview, right_no_background, dimension_width, dimension_height, dimension_rotate, last_update_time, create_time) VALUES (%(aid)s, %(videos)s, %(tid)s, %(tname)s, %(copyright)s, %(pic)s, %(title)s, %(pubdate)s, %(ctime)s, %(desc)s, %(state)s, %(attribute)s, %(duration)s, %(mission_id)s, %(dynamic)s, %(cid)s, %(bvid)s, %(owner_mid)s, %(stat_aid)s, %(right_bp)s, %(right_elec)s, %(right_download)s, %(right_movie)s, %(right_pay)s, %(right_hd5)s, %(right_no_reprint)s, %(right_autoplay)s, %(right_ugc_pay)s, %(right_is_cooperation)s, %(right_ugc_pay_preview)s, %(right_no_background)s, %(dimension_width)s, %(dimension_height)s, %(dimension_rotate)s, %(last_update_time)s, %(create_time)s)]
[parameters: {'aid': 77683558, 'videos': 1, 'tid': 171, 'tname': '电子竞技', 'copyright': 1, 'pic': 'http://i1.hdslb.com/bfs/archive/c140e68f64f4944e5b7fdaf241c4864a9e9a7f91.jpg', 'title': 'LPL全明星周末D2娱乐表演赛', 'pubdate': datetime.datetime(2019, 12, 1, 15, 34, 3, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'ctime': datetime.datetime(2019, 12, 1, 15, 34, 3, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'desc': 'LPL全明星周末D2娱乐表演赛', 'state': 0, 'attribute': 16512, 'duration': 4114, 'mission_id': -1, 'dynamic': '#电子竞技##英雄联盟##LPL全明星#LPL全明星周末D2娱乐表演赛', 'cid': 132899853, 'bvid': '', 'owner_mid': 50329118, 'stat_aid': 77683558, 'right_bp': 0, 'right_elec': 0, 'right_download': 0, 'right_movie': 0, 'right_pay': 0, 'right_hd5': 0, 'right_no_reprint': 1, 'right_autoplay': 1, 'right_ugc_pay': 0, 'right_is_cooperation': 0, 'right_ugc_pay_preview': 0, 'right_no_background': 0, 'dimension_width': 1920, 'dimension_height': 1080, 'dimension_rotate': 0, 'last_update_time': datetime.datetime(2019, 12, 2, 14, 13, 1, 612073, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800))), 'create_time': None}]
(Background on this error at: http://sqlalche.me/e/gkpj), aid: 77683558
2019-12-02 14:13:01,791 - [    INFO] - [          MainThread]   __init__.<module> - __init__.py[line:67] : Done
2019-12-02 14:18:06,239 - [    INFO] - [          MainThread]   __init__.<module> - __init__.py[line:67] : Done
2019-12-02 14:28:10,034 - [    INFO] - [          MainThread]   __init__.<module> - __init__.py[line:67] : Done
2019-12-02 14:28:10,034 - [    INFO] - [          MainThread]   __init__.<module> - __init__.py[line:67] : Done
2019-12-02 14:38:14,303 - [    INFO] - [          MainThread]   __init__.<module> - __init__.py[line:67] : Done
2019-12-02 14:38:14,303 - [    INFO] - [          MainThread]   __init__.<module> - __init__.py[line:67] : Done
2019-12-02 14:38:14,303 - [    INFO] - [          MainThread]   __init__.<module> - __init__.py[line:67] : Done
2019-12-02 14:48:20,183 - [    INFO] - [          MainThread]   __init__.<module> - __init__.py[line:67] : Done
2019-12-02 14:48:20,183 - [    INFO] - [          MainThread]   __init__.<module> - __init__.py[line:67] : Done
2019-12-02 14:48:20,183 - [    INFO] - [          MainThread]   __init__.<module> - __init__.py[line:67] : Done
2019-12-02 14:48:20,183 - [    INFO] - [          MainThread]   __init__.<module> - __init__.py[line:67] : Done
